name: Publish to PyPI
on: 
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  build-n-publish:
    name: Build and publish to PyPI and TestPyPI
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install poetry
      run: pipx install poetry

    - name: Build source tarball
      run: |
          rm -rf dist;
          poetry build

    - name: Config Test PyPI
      run: |
          poetry config repositories.testpypi https://test.pypi.org/legacy/
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_TOKEN }}

    - name: Publish distribution to Test PyPI
      run: poetry publish -r testpypi

    - name: Config PyPI
      run: poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

    - name: Publish distribution to PyPI
      if: startsWith(github.ref, 'refs/tags')
      run: poetry publish
